# Generated by Django 6.0.5 on 2026-05-05 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_unit_profile_flashcard_unit_unitprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='example',
            field=models.TextField(blank=True, verbose_name='Example sentence'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ipa',
            field=models.CharField(blank=True, max_length=120, verbose_name='IPA pronunciation'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('next_review', models.DateField(default=django.utils.timezone.now)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vocab.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
